# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest2():
    def setup_method(self, method):
        self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub',
                                       desired_capabilities=DesiredCapabilities.CHROME)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test2(self):
        # Test name: test_2
        # Step # | name | target | value
        # 1 | open | /ru/ |
        self.driver.get("http://selenium1py.pythonanywhere.com/ru/")
        # 2 | setWindowSize | 939x786 |
        self.driver.set_window_size(939, 786)
        # 3 | click | id=login_link |
        self.driver.find_element(By.ID, "login_link").click()
        # 4 | click | id=id_registration-email |
        self.driver.find_element(By.ID, "id_registration-email").click()
        # 5 | click | id=id_registration-email |
        self.driver.find_element(By.ID, "id_registration-email").click()
        # 6 | type | id=id_registration-email | isheiter1111@mail.ru
        self.driver.find_element(By.ID, "id_registration-email").send_keys("isheiter1111@mail.ru")
        # 7 | click | id=id_registration-password1 |
        self.driver.find_element(By.ID, "id_registration-password1").click()
        # 8 | type | id=id_registration-password1 | qwertyuio
        self.driver.find_element(By.ID, "id_registration-password1").send_keys("qwertyuio")
        # 9 | click | id=id_registration-password2 |
        self.driver.find_element(By.ID, "id_registration-password2").click()
        # 10 | type | id=id_registration-password2 | qwertyuio
        self.driver.find_element(By.ID, "id_registration-password2").send_keys("qwertyuio")
        # 11 | click | name=registration_submit |
        self.driver.find_element(By.NAME, "registration_submit").click()
        # 12 | click | id=id_registration-password1 |
        self.driver.find_element(By.ID, "id_registration-password1").click()
        # 13 | type | id=id_registration-password1 | qawsedrft
        self.driver.find_element(By.ID, "id_registration-password1").send_keys("qawsedrft")
        # 14 | click | id=id_registration-password2 |
        self.driver.find_element(By.ID, "id_registration-password2").click()
        # 15 | type | id=id_registration-password2 | qawsedrft
        self.driver.find_element(By.ID, "id_registration-password2").send_keys("qawsedrft")
        # 16 | click | name=registration_submit |
        self.driver.find_element(By.NAME, "registration_submit").click()

